-- =====================================================================
-- Scientific Tumbleweed — application schema bootstrap
--
-- Generated by scripts/emit_init_sql.py from SQLModel metadata.
-- Do NOT edit by hand. Run ``make emit-init-sql`` after changing any
-- file under backend/packages/harness/deerflow/db/models/.
--
-- This script runs exactly once, when the Postgres data volume is
-- empty. deerflow.db.setup.ensure_schema() re-applies the same DDL
-- on every gateway startup as an idempotent safety net, so having
-- both mechanisms is intentional.
--
-- LangGraph's own tables (checkpoints*, store*) are created at
-- runtime by langgraph-checkpoint-postgres and are NOT listed here.
-- =====================================================================

-- Extensions ---------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pg_search;
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

-- Application tables --------------------------------------------------
-- channel_threads
CREATE TABLE IF NOT EXISTS channel_threads (
	key VARCHAR NOT NULL, 
	thread_id VARCHAR NOT NULL, 
	user_id VARCHAR NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL, 
	PRIMARY KEY (key)
);

CREATE INDEX IF NOT EXISTS idx_channel_threads_key_prefix ON channel_threads (key text_pattern_ops);

-- tool_cache
CREATE TABLE IF NOT EXISTS tool_cache (
	cache_key VARCHAR NOT NULL, 
	tool_name VARCHAR NOT NULL, 
	value_json JSONB NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL, 
	expires_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (cache_key)
);

CREATE INDEX IF NOT EXISTS idx_tool_cache_expires_at ON tool_cache (expires_at);
CREATE INDEX IF NOT EXISTS ix_tool_cache_tool_name ON tool_cache (tool_name);

-- user_memory
CREATE TABLE IF NOT EXISTS user_memory (
	user_id VARCHAR NOT NULL, 
	data JSONB DEFAULT '{}'::jsonb NOT NULL, 
	version INTEGER NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL, 
	PRIMARY KEY (user_id)
);

CREATE INDEX IF NOT EXISTS idx_user_memory_data_gin ON user_memory USING gin (data);

-- users
CREATE TABLE IF NOT EXISTS users (
	id VARCHAR NOT NULL, 
	email VARCHAR NOT NULL, 
	username VARCHAR NOT NULL, 
	display_name VARCHAR NOT NULL, 
	password_hash VARCHAR, 
	system_role VARCHAR NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL, 
	oauth_provider VARCHAR, 
	oauth_id VARCHAR, 
	needs_setup BOOLEAN NOT NULL, 
	token_version INTEGER NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (email), 
	UNIQUE (username)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_oauth_identity ON users (oauth_provider, oauth_id) WHERE oauth_provider IS NOT NULL AND oauth_id IS NOT NULL;
