#!/usr/bin/env python3
"""Emit ``docker/postgres/init.sql`` from the SQLModel metadata.

The Postgres container runs ``/docker-entrypoint-initdb.d/10-init.sql``
exactly once, when the data volume is empty. That makes ``init.sql``
the authoritative bootstrap: new developers and new deployments get a
complete schema on first boot, without needing the application to
run ``ensure_schema()`` first.

Source of truth stays in Python (SQLModel ``metadata``). This script
compiles the metadata to Postgres-dialect DDL, stitches it together
with the extension bootstrap and a stable header, and writes the
result to ``docker/postgres/init.sql``.

Workflow::

    # After editing any table in backend/packages/harness/deerflow/db/models/:
    make emit-init-sql
    git diff docker/postgres/init.sql   # review
    git add docker/postgres/init.sql

CI runs ``make emit-init-sql`` and fails if the file is out of sync.
"""

from __future__ import annotations

import sys
from pathlib import Path

from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateIndex, CreateTable

# Repo layout: <repo>/scripts/emit_init_sql.py -> parents[1] == <repo>
REPO_ROOT = Path(__file__).resolve().parents[1]
HARNESS_SRC = REPO_ROOT / "backend" / "packages" / "harness"
if str(HARNESS_SRC) not in sys.path:
    sys.path.insert(0, str(HARNESS_SRC))

from deerflow.db.models import metadata  # noqa: E402
from deerflow.db.setup import EXTENSIONS_DDL  # noqa: E402


OUTPUT_PATH = REPO_ROOT / "docker" / "postgres" / "init.sql"

HEADER = """\
-- =====================================================================
-- Scientific Tumbleweed — application schema bootstrap
--
-- Generated by scripts/emit_init_sql.py from SQLModel metadata.
-- Do NOT edit by hand. Run ``make emit-init-sql`` after changing any
-- file under backend/packages/harness/deerflow/db/models/.
--
-- This script runs exactly once, when the Postgres data volume is
-- empty. deerflow.db.setup.ensure_schema() re-applies the same DDL
-- on every gateway startup as an idempotent safety net, so having
-- both mechanisms is intentional.
--
-- LangGraph's own tables (checkpoints*, store*) are created at
-- runtime by langgraph-checkpoint-postgres and are NOT listed here.
-- =====================================================================

"""


def _compile(obj) -> str:
    """Compile a DDL element to a standalone, lowercase-safe SQL string."""
    return str(obj.compile(dialect=postgresql.dialect())).strip()


def _as_if_not_exists(create_sql: str) -> str:
    """Rewrite ``CREATE TABLE foo (...)`` → ``CREATE TABLE IF NOT EXISTS foo (...)``.

    SQLAlchemy's ``CreateTable`` doesn't emit ``IF NOT EXISTS`` by
    default; we patch the prefix ourselves so init.sql is safe to
    re-run (e.g. if someone attaches an existing volume to a fresh
    container).
    """
    for marker in ("CREATE TABLE ", "CREATE UNLOGGED TABLE ", "CREATE TEMPORARY TABLE "):
        if create_sql.startswith(marker):
            remainder = create_sql[len(marker):]
            return marker[:-1] + " IF NOT EXISTS " + remainder
    return create_sql


def _index_ddl(index) -> str:
    """CreateIndex + force IF NOT EXISTS."""
    sql = _compile(CreateIndex(index))
    for marker in ("CREATE UNIQUE INDEX ", "CREATE INDEX "):
        if sql.startswith(marker):
            remainder = sql[len(marker):]
            return marker[:-1] + " IF NOT EXISTS " + remainder
    return sql


def render() -> str:
    """Return the full init.sql text for the current metadata."""
    parts: list[str] = [HEADER]

    parts.append("-- Extensions ---------------------------------------------------------\n")
    for stmt in EXTENSIONS_DDL:
        parts.append(f"{stmt};\n")
    parts.append("\n")

    parts.append("-- Application tables --------------------------------------------------\n")
    for table in metadata.sorted_tables:
        parts.append(f"-- {table.name}\n")
        parts.append(_as_if_not_exists(_compile(CreateTable(table))))
        parts.append(";\n\n")
        for index in sorted(table.indexes, key=lambda i: i.name or ""):
            parts.append(_index_ddl(index))
            parts.append(";\n")
        if table.indexes:
            parts.append("\n")

    return "".join(parts).rstrip() + "\n"


def main(argv: list[str]) -> int:
    check_only = "--check" in argv

    rendered = render()
    current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""

    if check_only:
        if rendered == current:
            print(f"OK: {OUTPUT_PATH.relative_to(REPO_ROOT)} matches SQLModel metadata")
            return 0
        print(
            f"DRIFT: {OUTPUT_PATH.relative_to(REPO_ROOT)} is out of sync with "
            "SQLModel metadata. Run `make emit-init-sql` and commit the result.",
            file=sys.stderr,
        )
        return 1

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)} ({len(rendered)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
